### ISSUE TITLE
link naar github repo is niet goed gesubmit

### ISSUE THREAD

**Issue by stgm** [Sjoerdie/Ragweek-Utrecht#1]

**Comment by Sjoerdie** [comment]
En nu?

**Comment by stgm** [comment]
Nou, het is niet de HTTP clone URL zoals in de instructies staat :-)

**Comment by Sjoerdie** [comment]
Ik dacht deze eerder goed te hebben toegevoegd, nu moet ie goed zijn! Klopt dit?

Groetjes,

Sjoerd
